#!/bin/bash
# Merge include files into single-file compiler for self-hosting verification
# The Pascal compiler doesn't support {$I} includes, so we pre-process them

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
COMPILER_DIR="$PROJECT_DIR/compiler"
INC_DIR="$COMPILER_DIR/inc"
OUTPUT="$COMPILER_DIR/tuxpascal.pas"

(
echo '{ TuxPascal - Self-hosting Pascal Compiler }'
echo '{ Written in Pascal, compiled by bootstrap }'
echo '{ Generated by merging include files - do not edit directly }'
echo ''
echo 'program TuxPascal;'
echo ''
cat "$INC_DIR/constants.inc"
cat "$INC_DIR/utility.inc"
cat "$INC_DIR/lexer.inc"
cat "$INC_DIR/symbols.inc"
cat "$INC_DIR/emitters.inc"
cat "$INC_DIR/runtime.inc"
cat "$INC_DIR/parser.inc"
cat "$INC_DIR/declarations.inc"
cat "$INC_DIR/main.inc"
) > "$OUTPUT"

echo "Generated $OUTPUT"
